# ==================== HYPRELAND ====================
monitor=,preferred,auto,1

# Environnement Wayland
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# Clavier français
input {
    kb_layout = fr
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
        tap-to-click = yes
    }
}

# Démarrage auto
exec-once = kitty &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# Décorations simples
decoration {
    rounding = 10
    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(1a1a1aee)
    }
    blur {
        enabled = true
        size = 8
        passes = 3
    }
}

*exec-once = waybar > /dev/null 2>&1 &

source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/exec.conf
