# ===== Thème sombre pour les applications GTK =====
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

exec-once = waybar &> /dev/null &

exec-once = mako
