# Hyprpaper - Fond d'écran
# Hyprpaper - Fond d'écran
# Hyprpaper - Configuration simplifiée
preload = /home/joe/Pictures/wallpapers/current.png
wallpaper = eDP-1, /home/joe/Pictures/wallpapers/current.png
# Optionnel : activer le splash text
splash = false
ipc = true
